// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from './client';
import type { CreateFolderData, CreateFolderResponse, DeleteFolderData, DeleteFolderResponse, GetFolderData, GetFolderResponse, UpdateFolderData, UpdateFolderResponse, CreateNoteData, CreateNoteResponse, DeleteNoteData, DeleteNoteResponse, GetNoteData, GetNoteResponse, UpdateNoteData, UpdateNoteResponse, GetRecentNotesData, GetRecentNotesResponse, SearchNotesData, SearchNotesResponse, GetAncestorsData, GetAncestorsResponse, GetChildrenData, GetChildrenResponse, GetRootData, GetRootResponse } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class NoteswikiService {
    public static createFolder<ThrowOnError extends boolean = true>(options?: Options<CreateFolderData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).post<CreateFolderResponse, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/notes/api/v1/folders',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }

    public static deleteFolder<ThrowOnError extends boolean = true>(options: Options<DeleteFolderData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).delete<DeleteFolderResponse, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/notes/api/v1/folders/{id}',
            ...options
        });
    }

    public static getFolder<ThrowOnError extends boolean = true>(options: Options<GetFolderData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).get<GetFolderResponse, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/notes/api/v1/folders/{id}',
            ...options
        });
    }

    public static updateFolder<ThrowOnError extends boolean = true>(options: Options<UpdateFolderData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).put<UpdateFolderResponse, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/notes/api/v1/folders/{id}',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }

    public static createNote<ThrowOnError extends boolean = true>(options?: Options<CreateNoteData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).post<CreateNoteResponse, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/notes/api/v1/notes',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }

    public static deleteNote<ThrowOnError extends boolean = true>(options: Options<DeleteNoteData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).delete<DeleteNoteResponse, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/notes/api/v1/notes/{id}',
            ...options
        });
    }

    public static getNote<ThrowOnError extends boolean = true>(options: Options<GetNoteData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).get<GetNoteResponse, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/notes/api/v1/notes/{id}',
            ...options
        });
    }

    public static updateNote<ThrowOnError extends boolean = true>(options: Options<UpdateNoteData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).put<UpdateNoteResponse, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/notes/api/v1/notes/{id}',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }

    public static getRecentNotes<ThrowOnError extends boolean = true>(options?: Options<GetRecentNotesData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<GetRecentNotesResponse, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/notes/api/v1/notes/recent',
            ...options
        });
    }

    public static searchNotes<ThrowOnError extends boolean = true>(options?: Options<SearchNotesData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<SearchNotesResponse, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/notes/api/v1/notes/search',
            ...options
        });
    }

    public static getAncestors<ThrowOnError extends boolean = true>(options: Options<GetAncestorsData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).get<GetAncestorsResponse, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/notes/api/v1/tree/ancestors/{id}',
            ...options
        });
    }

    public static getChildren<ThrowOnError extends boolean = true>(options: Options<GetChildrenData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).get<GetChildrenResponse, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/notes/api/v1/tree/children/{parentId}',
            ...options
        });
    }

    public static getRoot<ThrowOnError extends boolean = true>(options?: Options<GetRootData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<GetRootResponse, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/notes/api/v1/tree/root',
            ...options
        });
    }

}