// This file is auto-generated by @hey-api/openapi-ts

export type CreateFolderRequest = {
    unique: string;
    parentUnique?: string | null;
    name: string;
};

export type CreateNoteRequest = {
    unique: string;
    parentUnique?: string | null;
    title: string;
    content: string;
    tags: Array<string>;
};

export enum EventMessageTypeModel {
    DEFAULT = 'Default',
    INFO = 'Info',
    ERROR = 'Error',
    SUCCESS = 'Success',
    WARNING = 'Warning'
}

export type FolderModel = {
    unique: string;
    entityType: string;
    parentUnique?: string | null;
    name: string;
    createdDate: string;
};

export type NoteModel = {
    unique: string;
    entityType: string;
    parentUnique?: string | null;
    title: string;
    content: string;
    tags: Array<string>;
    createdDate: string;
    modifiedDate: string;
    createdBy: string;
    modifiedBy: string;
};

export type NotificationHeaderModel = {
    message: string;
    category: string;
    type: EventMessageTypeModel;
};

export type SearchResultsModel = {
    results: Array<NoteModel>;
    totalCount: number;
};

export type TreeItemModel = {
    id: string;
    name: string;
    entityType: string;
    hasChildren: boolean;
    isFolder: boolean;
    icon: string;
    parentId?: string | null;
};

export type TreeResponseModel = {
    items: Array<TreeItemModel>;
    total: number;
};

export type UpdateFolderRequest = {
    name: string;
};

export type UpdateNoteRequest = {
    title: string;
    content: string;
    tags: Array<string>;
};

export type CreateFolderData = {
    body?: CreateFolderRequest;
    path?: never;
    query?: never;
    url: '/umbraco/notes/api/v1/folders';
};

export type CreateFolderErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type CreateFolderResponses = {
    /**
     * Created
     */
    201: FolderModel;
};

export type CreateFolderResponse = CreateFolderResponses[keyof CreateFolderResponses];

export type DeleteFolderData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/notes/api/v1/folders/{id}';
};

export type DeleteFolderErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type DeleteFolderResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteFolderResponse = DeleteFolderResponses[keyof DeleteFolderResponses];

export type GetFolderData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/notes/api/v1/folders/{id}';
};

export type GetFolderErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type GetFolderResponses = {
    /**
     * OK
     */
    200: FolderModel;
};

export type GetFolderResponse = GetFolderResponses[keyof GetFolderResponses];

export type UpdateFolderData = {
    body?: UpdateFolderRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/notes/api/v1/folders/{id}';
};

export type UpdateFolderErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type UpdateFolderResponses = {
    /**
     * OK
     */
    200: FolderModel;
};

export type UpdateFolderResponse = UpdateFolderResponses[keyof UpdateFolderResponses];

export type CreateNoteData = {
    body?: CreateNoteRequest;
    path?: never;
    query?: never;
    url: '/umbraco/notes/api/v1/notes';
};

export type CreateNoteErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type CreateNoteResponses = {
    /**
     * Created
     */
    201: NoteModel;
};

export type CreateNoteResponse = CreateNoteResponses[keyof CreateNoteResponses];

export type DeleteNoteData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/notes/api/v1/notes/{id}';
};

export type DeleteNoteErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type DeleteNoteResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteNoteResponse = DeleteNoteResponses[keyof DeleteNoteResponses];

export type GetNoteData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/notes/api/v1/notes/{id}';
};

export type GetNoteErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type GetNoteResponses = {
    /**
     * OK
     */
    200: NoteModel;
};

export type GetNoteResponse = GetNoteResponses[keyof GetNoteResponses];

export type UpdateNoteData = {
    body?: UpdateNoteRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/notes/api/v1/notes/{id}';
};

export type UpdateNoteErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type UpdateNoteResponses = {
    /**
     * OK
     */
    200: NoteModel;
};

export type UpdateNoteResponse = UpdateNoteResponses[keyof UpdateNoteResponses];

export type GetRecentNotesData = {
    body?: never;
    path?: never;
    query?: {
        count?: number;
    };
    url: '/umbraco/notes/api/v1/notes/recent';
};

export type GetRecentNotesErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetRecentNotesResponses = {
    /**
     * OK
     */
    200: Array<NoteModel>;
};

export type GetRecentNotesResponse = GetRecentNotesResponses[keyof GetRecentNotesResponses];

export type SearchNotesData = {
    body?: never;
    path?: never;
    query?: {
        q?: string;
    };
    url: '/umbraco/notes/api/v1/notes/search';
};

export type SearchNotesErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type SearchNotesResponses = {
    /**
     * OK
     */
    200: SearchResultsModel;
};

export type SearchNotesResponse = SearchNotesResponses[keyof SearchNotesResponses];

export type GetAncestorsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/notes/api/v1/tree/ancestors/{id}';
};

export type GetAncestorsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetAncestorsResponses = {
    /**
     * OK
     */
    200: Array<TreeItemModel>;
};

export type GetAncestorsResponse = GetAncestorsResponses[keyof GetAncestorsResponses];

export type GetChildrenData = {
    body?: never;
    path: {
        parentId: string;
    };
    query?: {
        skip?: number;
        take?: number;
    };
    url: '/umbraco/notes/api/v1/tree/children/{parentId}';
};

export type GetChildrenErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetChildrenResponses = {
    /**
     * OK
     */
    200: TreeResponseModel;
};

export type GetChildrenResponse = GetChildrenResponses[keyof GetChildrenResponses];

export type GetRootData = {
    body?: never;
    path?: never;
    query?: {
        skip?: number;
        take?: number;
    };
    url: '/umbraco/notes/api/v1/tree/root';
};

export type GetRootErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetRootResponses = {
    /**
     * OK
     */
    200: TreeResponseModel;
};

export type GetRootResponse = GetRootResponses[keyof GetRootResponses];

export type ClientOptions = {
    baseUrl: 'https://localhost:44325' | (string & {});
};