// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetChildrenData, GetChildrenErrors, GetChildrenResponses, GetDateData, GetDateErrors, GetDateResponses, GetRootData, GetRootErrors, GetRootResponses, GetTimeData, GetTimeErrors, GetTimeResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class TimedashboardService {
    public static getDate<ThrowOnError extends boolean = false>(options?: Options<GetDateData, ThrowOnError>) {
        return (options?.client ?? client).get<GetDateResponses, GetDateErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/timedashboard/api/v1/time/date',
            ...options
        });
    }

    public static getTime<ThrowOnError extends boolean = false>(options?: Options<GetTimeData, ThrowOnError>) {
        return (options?.client ?? client).get<GetTimeResponses, GetTimeErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/timedashboard/api/v1/time/time',
            ...options
        });
    }

    public static getChildren<ThrowOnError extends boolean = false>(options?: Options<GetChildrenData, ThrowOnError>) {
        return (options?.client ?? client).get<GetChildrenResponses, GetChildrenErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/timedashboard/api/v1/tree',
            ...options
        });
    }

    public static getRoot<ThrowOnError extends boolean = false>(options?: Options<GetRootData, ThrowOnError>) {
        return (options?.client ?? client).get<GetRootResponses, GetRootErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/timedashboard/api/v1/tree/root',
            ...options
        });
    }
}
