// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://localhost:44325' | (string & {});
};

export type PagedTimeTreeItemResponseModel = {
    total: number;
    items: Array<TimeTreeItemResponseModel>;
};

export type ReferenceByIdModel = {
    id: string;
};

export type TimeTreeItemResponseModel = {
    id: string;
    parent?: ReferenceByIdModel | null;
    name: string;
    type: string;
    hasChildren: boolean;
};

export type GetDateData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/timedashboard/api/v1/time/date';
};

export type GetDateErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetDateResponses = {
    /**
     * OK
     */
    200: string;
};

export type GetDateResponse = GetDateResponses[keyof GetDateResponses];

export type GetTimeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/timedashboard/api/v1/time/time';
};

export type GetTimeErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetTimeResponses = {
    /**
     * OK
     */
    200: string;
};

export type GetTimeResponse = GetTimeResponses[keyof GetTimeResponses];

export type GetChildrenData = {
    body?: never;
    path?: never;
    query?: {
        parentId?: string;
        skip?: number;
        take?: number;
    };
    url: '/umbraco/timedashboard/api/v1/tree';
};

export type GetChildrenErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetChildrenResponses = {
    /**
     * OK
     */
    200: PagedTimeTreeItemResponseModel;
};

export type GetChildrenResponse = GetChildrenResponses[keyof GetChildrenResponses];

export type GetRootData = {
    body?: never;
    path?: never;
    query?: {
        skip?: number;
        take?: number;
    };
    url: '/umbraco/timedashboard/api/v1/tree/root';
};

export type GetRootErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetRootResponses = {
    /**
     * OK
     */
    200: PagedTimeTreeItemResponseModel;
};

export type GetRootResponse = GetRootResponses[keyof GetRootResponses];
